DROP TABLE IF EXISTS `groups`;
CREATE TABLE `groups` (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(10) UNIQUE
);

DROP TABLE IF EXISTS teachers;
CREATE TABLE teachers (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
fullname VARCHAR(50)
);

DROP TABLE IF EXISTS students;
CREATE TABLE students (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, 
fullname VARCHAR(30) UNIQUE, 
group_id INTEGER,
FOREIGN KEY(group_id) REFERENCES `groups`(id)
);

DROP TABLE IF EXISTS disciplines;
CREATE TABLE disciplines (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(20),
teacher_id INTEGER,
FOREIGN KEY(teacher_id) REFERENCES teachers (id)
);

DROP TABLE IF EXISTS grades;
CREATE TABLE grades (
id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
discipline_id INTEGER,
student_id INTEGER,
FOREIGN KEY(discipline_id) REFERENCES disciplines (id),
FOREIGN KEY(student_id) REFERENCES students (id),
grade INTEGER,
date_of DATE
);